### ISSUE TITLE
Tab Background

### ISSUE THREAD

**Issue by Mina-Mikhail** [florent37/BubbleTab#2]
I can't change the tab background, i replaced `android:background="@android:color/white"`  with my custom color but the background still white !!

**Comment by shahzad1** [comment]
I'm having the same issue, i'm also unable to change  background color of tab.
Can anybody help?

**Comment by florent37** [comment]
has you tried with 1.0.2 ?

**Comment by shahzad1** [comment]
It gives error while upgrading from 1.0.0 to 1.0.2
Failed to resolve: compile 'com.github.florent37:bubbletab:1.0.2'

**Comment by florent37** [comment]
can you try now ? I failed to upload
